### ISSUE TITLE
Analyzer 'ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer' is throwing IndexOutOfBoundException

### ISSUE THREAD

**Issue by ArsenyChernyaev** [olsh/resharper-structured-logging#48]
Could you please take a look at the exception?
```
Summary: Analyzer 'ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer' threw the following exception: Index was outside the bounds of the array.

Description:
JetBrains Rider 2021.3 Build RD-213.4631.30 Date 2021-10-08T14:16:31.524+0000

--- EXCEPTION #1/2 [IndexOutOfRangeException]
Message = â€œIndex was outside the bounds of the array.â€
ExceptionPath = Root.InnerException
ClassName = System.IndexOutOfRangeException
HResult = COR_E_INDEXOUTOFRANGE=80131508
Source = ReSharper.Structured.Logging.Rider
StackTraceString = â€œ
  at ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer.CheckComplexObjectInTemplate(IInvocationExpression element, IHighlightingConsumer consumer) in C:\projects\resharper-structured-logging\src\ReSharper.Structured.Logging\Analyzer\ComplexObjectDestructureAnalyzer.cs:line 61
     at ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer.Run(IInvocationExpression element, ElementProblemAnalyzerData data, IHighlightingConsumer consumer) in C:\projects\resharper-structured-logging\src\ReSharper.Structured.Logging\Analyzer\ComplexObjectDestructureAnalyzer.cs:line 34
     at JetBrains.ReSharper.Feature.Services.Daemon.ElementProblemAnalyzerRegistrar.ElementAnalyzerDispatcher.Run(ITreeNode element, IHighlightingConsumer consumer)
â€

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = â€œAnalyzer 'ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer' threw the following exception: Index was outside the bounds of the array.â€
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = â€œException #1 at Root.InnerExceptionâ€
HResult = COR_E_APPLICATION=80131600
StackTraceString = â€œ
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     at JetBrains.Util.Logging.Logger.LogException(String comment, Exception ex)
     at JetBrains.ReSharper.Feature.Services.Daemon.ElementProblemAnalyzerRegistrar.ElementAnalyzerDispatcher.Run(ITreeNode element, IHighlightingConsumer consumer)
     at JetBrains.ReSharper.Daemon.CSharp.Stages.CSharpErrorStageProcess.ProcessAfterInterior(ITreeNode element, IHighlightingConsumer consumer)
     at JetBrains.ReSharper.Psi.RecursiveElementProcessorExtensions.ProcessDescendants(ITreeNode root, IRecursiveElementProcessor processor)
     at JetBrains.ReSharper.Psi.RecursiveElementProcessorExtensions.ProcessThisAndDescendants(ITreeNode root, IRecursiveElementProcessor processor)
     at JetBrains.ReSharper.Daemon.CSharp.Stages.CSharpIncrementalDaemonStageProcessBase.<>c__DisplayClass4_0.<Execute>g__MemberHighlighter|0(ICSharpTypeMemberDeclaration declaration)
     at JetBrains.ReSharper.Psi.Extensions.<>c__DisplayClass0_0.<EnqueueJob>b__0()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask()
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc()
     at JetBrains.Util.Reflection.CallStackAnnotation.CatchAnnotatedInvocation[TClassOfNewFrame](String methodNameOfNewFrame, Action actionToAnnotate)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
â€


last.action = null

app.eap = true
app.internal = false
app.build = RD-213.4631.30
app.version.major = 2021
app.version.minor = 3
app.build.date = 2021-10-08T14:16:31.524+0000
app.build.date.release = 2021-12-01T00:00:31.524+0000
app.build.date.release = 2021-12-01T00:00:31.524+0000
app.product.code = RD

os.name = Windows 10
os.cpu.arch = amd64
java.version = 11.0.12
java.vm.vendor = JetBrains s.r.o.

UIUtil.isRetina = false
JBUI.isHiDPI() = false
ImageScaleFactor = 1

netcore = false

.NET Framework 4.0.30319.42000
```

**Comment by olsh** [comment]
Hi guys,

Sorry for the delay. I managed to reproduce it, will fix it soon.
Thank you for your help! 👍🏻
