### ISSUE TITLE
Exception in ComplexObjectDestructureAnalyzer.CheckComplexObjectInTemplate

### ISSUE THREAD

**Issue by auduchinok** [olsh/resharper-structured-logging#52]
Hi, just wanted to let you know that there have been many exception reports with the following stack trace recently:

```
JetBrains Rider 2021.2.1 Build RD-212.5080.71 Date 2021-08-26T12:44:28.230+0000

--- EXCEPTION #1/2 [IndexOutOfRangeException]
Message = “Index was outside the bounds of the array.”
ExceptionPath = Root.InnerException
ClassName = System.IndexOutOfRangeException
HResult = COR_E_INDEXOUTOFRANGE=80131508
Source = ReSharper.Structured.Logging.Rider

StackTraceString = “
  at ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer.CheckComplexObjectInTemplate(IInvocationExpression element, IHighlightingConsumer consumer) in C:\projects\resharper-structured-logging\src\ReSharper.Structured.Logging\Analyzer\ComplexObjectDestructureAnalyzer.cs:line 61
     at ReSharper.Structured.Logging.Analyzer.ComplexObjectDestructureAnalyzer.Run(IInvocationExpression element, ElementProblemAnalyzerData data, IHighlightingConsumer consumer) in C:\projects\resharper-structured-logging\src\ReSharper.Structured.Logging\Analyzer\ComplexObjectDestructureAnalyzer.cs:line 34
     at JetBrains.ReSharper.Feature.Services.Daemon.ElementProblemAnalyzerRegistrar.ElementAnalyzerDispatcher.Run(ITreeNode element, IHighlightingConsumer consumer)
”
```

**Comment by olsh** [comment]
Hi @auduchinok, I believe that this is related to #48.
This issue is fixed in the latest EAP version.

**Comment by auduchinok** [comment]
Oh, sorry for duplicating it, I should've checked closed issues.

Thanks for fixing it! 🙂
