### ISSUE TITLE
Specified cast is not valid on reading `ConstantValue.StringValue`

### ISSUE THREAD

**Issue by van800** [olsh/resharper-structured-logging#83]
corresponding automatic exception report https://youtrack.jetbrains.com/issue/DEXP-708411/Analyzer-ReSharper.Structured.Logging.Analyzer.PropertiesNamingAnalyzer-threw-the-following-exception-Specified-cast-is-not

Similar fix in the Unity support plugin:
https://github.com/JetBrains/resharper-unity/commit/e9df0000ed708d8250f5ede98f6685c4c4e9ac23

**Comment by olsh** [comment]
Hi @van800 
Could you please attach the stack trace?

**Comment by van800** [comment]
StackTraceString = “
  at JetBrains.ReSharper.Psi.ConstantValue.get_StringValue()
     at ReSharper.Structured.Logging.Analyzer.PropertiesNamingAnalyzer.CheckPropertiesInContext(IInvocationExpression element, IHighlightingConsumer consumer, IContextBoundSettingsStore settingsStore, Regex ignoredPropertiesRegex) in C:\projects\resharper-structured-logging\src\ReSharper.Structured.Logging\Analyzer\PropertiesNamingAnalyzer.cs:line 92
     at JetBrains.ReSharper.Feature.Services.Daemon.ElementProblemAnalyzerRegistrar.ElementAnalyzerDispatcher.Run(ITreeNode element, IHighlightingConsumer consumer) in Run.il:line IL_0063 mvid ABDB

**Comment by van800** [comment]
I think this query on youtrack would show you all the related reports 
https://youtrack.jetbrains.com/issues?q=%22resharper-structured-logging%22%20JetBrains.ReSharper.Psi.ConstantValue.get_StringValue

**Comment by olsh** [comment]
Huh, this is a pretty old bug. I'll take a look.
Thanks.

**Comment by van800** [comment]
Previously this was never a problem, because only string was allowed for the attribute parameter value.
New dotnet/langversion allows setting const or string interpolation there. Like in my case:
![image](https://user-images.githubusercontent.com/1482681/222437525-bb87e610-0d9c-4d23-a062-353c42eaec0c.png)
